name: vypervic_v2
description: V2 Trading Engine Mobile

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.2.1
  telegram_client: ^1.0.0
  charts_flutter: ^0.12.0
  shared_preferences: ^2.3.2
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
